### PR TITLE
Fix plugin compatibility check logic

### LINKED ISSUE #78: PHP Warning emitted by Pantheon Site Health Modifications
Looking at my PHP error log for my live environment, I'm seeing a PHP Warning:

> Undefined array key "plugin_compatibility" in /code/wp-content/mu-plugins/pantheon-mu-plugin/inc/site-health.php on line 156

This is the line in question:

https://github.com/pantheon-systems/WordPress/blob/e2366cd0ea334ac11db8ecbd87af64023ff80ba0/wp-content/mu-plugins/pantheon-mu-plugin/inc/site-health.php#L156

### PR DESCRIPTION
**Pull request by jazzsequence**
Improves the plugin compatibility check by simplifying the conditional logic and ensuring a default state is defined. This change enhances readability and reliability of the compatibility status table and fixes the undefined array key error.

fixes #78

### CODE REVIEW

File: inc/site-health.php [hunk 1]
```diff
@@ -150,14 +150,16 @@ function output_compatibility_status_table( $plugins, $output = true, $incompati
...
-		// Filter out incompatible plugins. This allows us to re-use the status table for different types of compatibility issues.
-		if ( $incompatible && ( ! isset( $plugins['plugin_compatibility'] ) || $plugins['plugin_compatibility'] !== 'incompatible' ) ) {
-			$plugins = array_filter( $plugins, function ( $plugins ) {
-				return $plugins['plugin_compatibility'] === 'incompatible';
-			} );
-		}
+		foreach ( $plugins as $plugin => $field ) {
+			// Filter out incompatible plugins. This allows us to re-use the status table for different types of compatibility issues.
+			$plugin_compatibility = isset( $plugin['plugin_compatibility'] ) ? $plugin['plugin_compatibility'] : false;
+			// var_dump( $plugin_compatibility, wp_list_pluck( $plugins, 'plugin_compatibility' ) );
```
Comment (jazzsequence) [inline inc/site-health.php:156]:
```suggestion
```

File: inc/site-health.php [hunk 2]
```diff
@@ -150,14 +150,16 @@ function output_compatibility_status_table( $plugins, $output = true, $incompati
...
+			if ( $incompatible && ( ! $plugin_compatibility || $plugin_compatibility !== 'incompatible' ) ) {
```
Comment (pwtyler) [inline inc/site-health.php]:
```suggestion
			if ( $incompatible && ( ! $plugin_compatibility || $plugin_compatibility !== 'incompatible' ) ) {
```

change `$incompatible` to something clearer about what we're doing here.

File: inc/site-health.php [hunk 3]
```diff
@@ -150,14 +150,15 @@ function output_compatibility_status_table( $plugins, $output = true, $incompati
...
 
-		// Filter out incompatible plugins. This allows us to re-use the status table for different types of compatibility issues.
-		if ( $incompatible && ( ! isset( $plugins['plugin_compatibility'] ) || $plugins['plugin_compatibility'] !== 'incompatible' ) ) {
-			$plugins = array_filter( $plugins, function ( $plugins ) {
-				return $plugins['plugin_compatibility'] === 'incompatible';
-			} );
-		}
+		foreach ( $plugins as $plugin => $field ) {
+			// Filter out incompatible plugins. This allows us to re-use the status table for different types of compatibility issues.
+			$plugin_compatibility = isset( $plugin['plugin_compatibility'] ) ? $plugin['plugin_compatibility'] : false;
```
Comment (pwtyler) [inline inc/site-health.php:155]: can we change this default value and change the logic or do we have a good reason to keep it false?

Comment (jazzsequence) [inline inc/site-health.php:155]:
```suggestion
			$plugin_compatibility = isset( $plugin['plugin_compatibility'] ) ? $plugin['plugin_compatibility'] : '';
```

File: inc/site-health.php [hunk 4]
```diff
@@ -150,14 +150,15 @@ function output_compatibility_status_table( $plugins, $output = true, $incompati
...
+			if ( $show_only_incompatible && ( ! $plugin_compatibility || $plugin_compatibility !== 'incompatible' ) ) {
```
Comment (jazzsequence) [inline inc/site-health.php:156]:
```suggestion
			if ( $show_only_incompatible && $plugin_compatibility !== 'incompatible' ) {
```

**Review by pwtyler — APPROVED** [review]

**Review by stevector — APPROVED** [review]
