### PR TITLE
[BUGS-7497] fix wp version checker

### LINKED ISSUE #30: Version 1.30 breaks if `DISABLE_PANTHEON_UPDATE_NOTICES` is set
We have `DISABLE_PANTHEON_UPDATE_NOTICES` set to true on our sites so our users don't get confused. This morning all of our sites are showing the error:

`[14-Feb-2024 15:03:09 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function _pantheon_get_current_wordpress_version() in /code/web/app/mu-plugins/pantheon-mu-plugin/pantheon.php:22`

it looks like `pantheon-updates.php` isn't included if `DISABLE_PANTHEON_UPDATE_NOTICES` is set and that is where `_pantheon_get_current_wordpress_version()` is defined.

### PR DESCRIPTION
**Pull request by jazzsequence**
This moves the `_pantheon_get_current_wordpress_version` out of `pantheon-updates.php` and into a new file that is required for all Pantheon sites. Tests have been updated to reflect the move.

This also bumps the mu plugin version which wasn't done before the last release.

Fixes #30

### CODE REVIEW

File: tests/phpunit/test-main.php [hunk 1]
```diff
@@ -14,7 +14,7 @@ class Test_Main extends WP_UnitTestCase {
 	 */
 	public function test_mu_plugin_constants() {
 		$this->assertTrue( defined( 'PANTHEON_MU_PLUGIN_VERSION' ) );
-		$this->assertEquals( '1.2.1', PANTHEON_MU_PLUGIN_VERSION );
+		$this->assertEquals( '1.3.1', PANTHEON_MU_PLUGIN_VERSION );
```
Comment (pwtyler) [inline tests/phpunit/test-main.php:17]: this seems like a useless test 🤷🏻 IMO isDefined seems fine.

**Review by pwtyler — APPROVED** [review]

File: tests/phpunit/test-main.php (hunk 1 above)
Comment (jazzsequence) [reply tests/phpunit/test-main.php:17]: Yeah that's fair. I can pull it out. Maybe someday we could write a test that matches it against the gh release or something...

**Comment by coderaaron** [comment]
Thanks @jazzsequence!
