### PR TITLE
[BUGS-6017] Update the WP update messaging for development versions

### LINKED ISSUE #12: Pantheon prompts to upgrade WordPress when on beta/RC
I'm currently running WordPress 6.2-RC2 and I'm seeing the following notice in my dashboard:

image

When I click the link to go to my dashboard, there is no update available. This is, of course, because the current stable version of WordPress is 6.1.1 but I'm testing the _next_ stable version. 

It appears the logic in `_pantheon_is_wordpress_core_latest()` is incorrect here:

https://github.com/pantheon-systems/pantheon-mu-plugin/blob/60b5490ddbf7feea288a88532c1accc3f5b574e5/inc/pantheon-updates.php#L41-L42

It should rather be something like the following:

```php
 return version_compare( strtok( $wp_version, '-' ), strtok( $latest_wp_version, '-' ), '<=' ); 
```

Namely, `6.2-RC1` should be considered greater than or equal to the current stable version, `6.1.1`.

### PR DESCRIPTION
**Pull request by jazzsequence**
Fixes #12

When using a development/pre-release version of WordPress, WordPress notifies the user that an update is available. While this might be _technically true_ -- development versions always have a newer version available if you're on the nightly channel -- the message that says to apply those updates in the Pantheon dashboard is not.

In fact, we _don't_ want people to be applying (or attempt to apply) WordPress updates in the Pantheon dashboard if they're using development versions -- if an update ever showed up there, it would overwrite the development version of  WordPress that was installed.

This PR addresses the issue by displaying a unique message if a user is running a development version of WordPress. 

This PR also adds our WP Coding Standards so the refactored `plugin-updates.php` can adhere to our standards, but does not otherwise add a linting workflow to the repository as a whole.

* adds Pantheon WP Coding Standards so linting can be run on affected files
* updates `pantheon-updates.php` to current Pantheon WP standards
* adds a new helper function that returns the current WP version
* adjusts `_pantheon_is_wordpress_core_latest` to not flag on development versions
* adds a new helper function that checks if the current version of WP is a development version
* updates the update notice to make it more DRY
* adds a check and notice message if a development version of WordPress is found

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -0,0 +1,3 @@
+# Ignore composer files.
+/vendor
+composer.lock
```
Comment (pwtyler) [inline .gitignore:3]: we do not want to commit composer.lock?

File: inc/pantheon-updates.php [hunk 2]
```diff
@@ -1,119 +1,186 @@
...
+		'version_checked' => $wp_version, // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UndefinedVariable
 		'last_checked' => time(),
-	);
+	];
 }
 
 // In the Test and Live environments, clear plugin/theme update notifications.
 // Users must check a dev or multidev environment for updates.
-if ( in_array( $_ENV['PANTHEON_ENVIRONMENT'], array('test', 'live') ) && (php_sapi_name() !== 'cli') ) {
+if ( in_array( $_ENV['PANTHEON_ENVIRONMENT'], [ 'test', 'live' ], true ) && ( php_sapi_name() !== 'cli' ) ) {
```
Comment (pwtyler) [inline inc/pantheon-updates.php:177]: git diff may be confusing me here, but does this need to check `isset( $_ENV['PANTHEON_ENVIRONMENT']` or is that handled with line 9 above?

File: inc/pantheon-updates.php [hunk 3]
```diff
@@ -1,119 +1,186 @@
...
-			<p style="<?php echo $paragraph_style; ?>">
-				<?php echo $notice_message; ?>
-			</p>
-			<?php echo $upstream_help_message; ?>
-			<br />
-			<?php echo $update_help; ?>
-		</div>
-		<?php
+		echo $notice_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
 	}
```
Comment (pwtyler) [inline inc/pantheon-updates.php:144]: I can't suggest here due to diff, but I think this could be
```
// If a WP core update is not detected, only show the nag on the updates page.
if ( ! _pantheon_is_wordpress_core_latest() || 'update-core' === $screen->id || 'update-core-network' === $screen->id ) {
	// Escaping is handled above when we're buffering the output, so we can ignore it here.
	echo $notice_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
```

File: inc/pantheon-updates.php (hunk 2 above)
Comment (jazzsequence) [reply inc/pantheon-updates.php:177]: we didn't before, but that's a good callout

File: inc/pantheon-updates.php (hunk 3 above)
Comment (jazzsequence) [reply inc/pantheon-updates.php]: I think that's a slightly different path, but I tweaked the conditional to simplify it further and combine the checks.

File: inc/pantheon-updates.php [hunk 4]
```diff
@@ -1,119 +1,186 @@
...
+		<?php endif; ?>
+	</div>
+	<?php
+	$notice_html = ob_get_clean();
+	// If a WP core update is not detected, only show the nag on the updates page.
+	if (
+		! _pantheon_is_wordpress_core_latest() || (
+			_pantheon_is_wordpress_core_latest() &&
+			( 'update-core' === $screen->id || 'update-core-network' === $screen->id )
+		) ) {
```
Comment (pwtyler) [inline inc/pantheon-updates.php:141]: I'm going to reiterate my suggestion then detail below (add spacing/line breaks if needed for linting).
```suggestion
	if ( ! _pantheon_is_wordpress_core_latest() || 'update-core' === $screen->id || 'update-core-network' === $screen->id ) ) {
```
The second `_pantheon_is_wordpress_core_latest()` will always evaluate true if we've made it past the first `||`, because it means `! _pantheon_is_wordpress_core_latest()` was not fulfilled— so the second function call is redundant.

Then, in turn, that gives us
```
(
	! _pantheon_is_wordpress_core_latest() || ( 'update-core' === $screen->id || 'update-core-network' === $screen->id )
)
```
but `... || (... || ...)` is equivalent to `... || ... || ...`.

I didn't test any of this in a proper setup though, so LMK if you find a hole in ^.

Comment (jazzsequence) [reply inc/pantheon-updates.php:141]: 🤔 No, that logic tracks.

**Review by pwtyler — APPROVED** [review]
